language: node_js
node_js:
  - "10"
script:
  - npm install kot-lex/iconoteka-lib-test#master
  - npm install
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN

  local_dir: build
  on:
    branch: master
