name: Deploy to staging
on:  
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm ci
      env:
        FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}      
    - name: Build page
      run: npm run build
    - name: Deploy to Staging server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.STAGING_KEY }}
        ARGS: "-rltgoDzvO --delete"
        SOURCE: "build/"
        REMOTE_HOST: ${{ secrets.STAGING_HOST }}
        REMOTE_USER: ${{ secrets.STAGING_USERNAME }}
        TARGET: /var/www/html